# Generated by Django 2.2.27 on 2024-02-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_auto_20240121_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbookbot',
            name='now_chatroom_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='當前聊天房間'),
        ),
    ]
