# Generated by Django 2.2.27 on 2024-02-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_auto_20240105_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='性別'),
        ),
    ]
