# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Test0110

on:
  push:
    branches:
      - ci部屬
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
  
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
  
      - name: Install dependencies
        run: pip install -r requirements_ci.txt
  
      - name: Database migrations
        run: python manage.py migrate
  
      - name: Run tests
        run: pytest